# Generated by Django 5.2.4 on 2025-08-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_customerorder_customerorderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderitems',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
