# Generated by Django 5.2.4 on 2025-08-05 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_customerorderitems_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.customerorder'),
        ),
    ]
